export type GiscusCommentConfig = {
	enabled: boolean;
	repo: `${string}/${string}`;
	repoId: string;
	category: string;
	categoryId: string;
	mapping: "pathname" | "url" | "title" | "og:title";
	strict: boolean;
	reactionsEnabled: boolean;
	inputPosition: "top" | "bottom";
	lang: string;
};

/**
 * giscus stores each post's comments in a GitHub Discussion.
 *
 * The repository and category IDs are public identifiers generated by giscus;
 * this file contains no GitHub token or account secret.
 */
export const commentConfig: GiscusCommentConfig = {
	enabled: true,
	repo: "heparidayo/Blog",
	repoId: "R_kgDOOZFHBQ",
	category: "Announcements",
	categoryId: "DIC_kwDOOZFHBc4DEQs-",
	mapping: "pathname",
	strict: true,
	reactionsEnabled: true,
	inputPosition: "top",
	lang: "ko",
} satisfies GiscusCommentConfig;
